version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgresGWhub
    restart: always
    ports:
      - "5432:5432"
    expose:
      - "5432"
    env_file:
      - ./.env
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: "tyria"

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: example@example.com
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    env_file:
      - ./.env